export const EcoBonApp = {
  title: 'EcoBón',
  slogan: 'https://docs.minimals.cc/changelog',
  version: 'https://docs.minimals.cc/changelog',
  welcomeText: 'Hola Bienvenido!',
  signInTitle: 'Inicia sesión en EcoBón',
  newUserText: '¿Nuevo usuario?',
  createNewAccount: 'Crea una nueva cuenta',
  placeHolderEmail: 'E-mail',
  placerHolderPassword: 'Pass',
  signInButton: 'Login',
  orSignInWith: 'O logeate con',
  signUpButton: 'Registrarse',
  forgotPassword: '¿Olvidaste tu pass?',
};
